#pragma once
#ifndef TOKIO_GUI_ICONS_HPP
#define TOKIO_GUI_ICONS_HPP

#include "Resources/FontAwesomeImpl.h"


#define ICON_TOKIO_SAVE                ICON_FA_SAVE
#define ICON_TOKIO_COPY                ICON_FA_COPY
#define ICON_TOKIO_GOTO_ADDRESS        ICON_FA_ARROW_RIGHT
#define ICON_TOKIO_FOLLOW_ADDRESS      ICON_FA_ARROW_FROM_TOP
#define ICON_TOKIO_FIND_REFERENCES     ICON_FA_SEARCH
#define ICON_TOKIO_SWITCH_MODE         ICON_FA_CHART_NETWORK
#define ICON_TOKIO_OPEN_FILE_LOCATION  ICON_FA_FOLDER_OPEN
#define ICON_TOKIO_FREEZE              ICON_FA_SNOWFLAKE
#define ICON_TOKIO_POWER_OFF           ICON_FA_POWER_OFF
#define ICON_TOKIO_REFRESH             ICON_FA_REDO

#define ICON_TOKIO_ATTACH_PROC         ICON_FA_BROWSER
#define ICON_TOKIO_SETTINGS            ICON_FA_COG
#define ICON_TOKIO_SYMBOL_LIST         ICON_FA_DATABASE
#define ICON_TOKIO_MEMORY_VIEW         ICON_FA_MEMORY
#define ICON_TOKIO_MEMORY_SCAN         ICON_FA_SEARCH
#define ICON_TOKIO_WATCH_LIST          ICON_FA_EYE
#define ICON_TOKIO_DISASSEMBLER        ICON_FA_MICROCHIP
#define ICON_TOKIO_PSEUDO_CODE         ICON_FA_CODE

#endif // !TOKIO_GUI_ICONS_HPP